# Generated by Django 5.0.2 on 2024-02-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='usuario',
        ),
    ]
