# Generated by Django 5.0.2 on 2024-02-10 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_rename_esprestado_livros_emprestado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimos',
            options={},
        ),
    ]
