# Generated by Django 5.0.2 on 2024-02-10 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_alter_emprestimos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimos',
            options={'verbose_name': 'Emprestimo'},
        ),
    ]
